name: OSX Workflow

# Manual deployment
on: workflow_dispatch

jobs:
  osx-build:
    name: osx-build
    runs-on: [self-hosted, X64, macOS]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      # Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install XCodes
        run: brew install robotsandpencils/made/xcodes

      # Checkout the Repository
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: ls
        run: ls -l /Users

      # Setup Ruby while Caching Gems
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true